version: "2"
services:
  cce:
    image: openlmis/cce
    links:
      - db
      - log
    ports:
      - "8080"
    env_file: .env
  db:
    image: openlmis/postgres:12-debezium
    env_file: .env
  log:
    image: openlmis/rsyslog:3
    volumes:
      - '../logs/cce:/var/log'
